controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

terms_and_conditions:
    path: /terms-and-conditions
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: terms_and_conditions.html.twig
    methods: [GET]